### ISSUE TITLE
Workflow 无法运行

### ISSUE THREAD

**Issue by sainho93** [cdpath/EuDic_tools#1]
使用该 Workflow 时欧路词典的窗口可以弹出，但是没有显示搜索结果。Alfred 的 debug 模式报错

```
[ERROR: alfred.workflow.action.script] 181:190: execution error: “System Events”遇到一个错误：不能将“process "EuDic"”设置为“true”。 (-10006)
``` 
* OS X 版本为 10.11.6
* Alfred 版本为v2.8.7

**Comment by cdpath** [comment]
@sainho93 欧路支持 AppleScript 了，请试一下[新版](https://github.com/cdpath/alfred/blob/master/workflows/Eudic.alfredworkflow)。

**Comment by Leslie307** [comment]
OS X 版本为 10.12.6
Alfred 版本为v3.4.1
下载最新版还是执行不了啊
debug 信息如下：
Starting debug for 'Eudic'

[2017-08-07 14:20:40][ERROR: action.script] 382:385: syntax error: 预期是––µƒΩ·Œ≤µ»µ»，却找到±Í ∂∑˚。 (-2741)
