### ISSUE TITLE
执行不了，show那行语句报错

### ISSUE THREAD

**Issue by Leslie307** [cdpath/EuDic_tools#2]
macOS Sierra 10.12
show dic with word "{query}"这行语句报错了，无法显示要查的词。（This statement is error）

**Comment by cdpath** [comment]
欧路词典是 Pro 还是 Lite？
更新了一下兼容 Pro 和 Lite 的 workflow，https://github.com/cdpath/eudic_tools/releases/tag/v1.4

**Comment by Leslie307** [comment]
并不是版本的问题，欧路词典能够被调起，进行了debug跟踪，是show dic with word "{query}"这个语句报错，这个语句执行不了，无法在欧路词典中显示要查的单词。在applescript文档并没有找到有关show的命令，请问这个语句的运行原理是什么？

**Comment by cdpath** [comment]
@Leslie307 请更新到 Eudic Version 3.6.5 (988)

**Comment by Leslie307** [comment]
升级到最新版，可以显示单词了，谢谢！
我还是想知道show那条语句是如何执行的。

**Comment by cdpath** [comment]
@Leslie307 Eudic 最近增加了对 AppleScript 的支持，可以通过 Script Editor -> Open Dictionary 查看：

![](https://user-images.githubusercontent.com/11472839/29445092-377d9a4a-8417-11e7-837f-391352f46a4c.png)

**Comment by Leslie307** [comment]
@cdpath 万分感谢🙏
